version: '3.8'

services:
  nestjs:
    build: .
    ports:
      - '8080:8080'
    environment:
      - NODE_ENV=production
    volumes:
      - .:/app
      - /app/node_modules
    restart: unless-stopped
